[package]
name = "Arcane"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"]}
anyhow = "1.0.100"
log = "0.4.28"
env_logger = "0.11.8"
reqwest = { version = "0.12.24", features = ["json"] }
